import { useEffect, useMemo, useState } from 'react';
import { useAuth } from '@/lib/AuthContext';
import StatusAdmin from './StatusAdmin';
import { getAdminReports, adminResolveReport, adminDeleteReport, adminBlockReporter, getAdminSpots, adminUpdateSpot, deleteSpotAsSuperAdmin, getAdminPOIPhotos, adminDeletePOIPhoto } from '@/api/firebaseClient';

const tabs = ['Reports','Spots','Photos','Status'];
export default function Admin(){
  const { user, isAdmin, isLoadingAuth } = useAuth();
  const [tab,setTab]=useState('Reports'); const [reports,setReports]=useState([]); const [spots,setSpots]=useState([]); const [photos,setPhotos]=useState([]); const [filter,setFilter]=useState('all'); const [typeFilter,setTypeFilter]=useState('all'); const [reasonFilter,setReasonFilter]=useState('all'); const [q,setQ]=useState('');
  const refresh=async()=>{ if(!isAdmin)return; const [r,s,p]=await Promise.all([getAdminReports(),getAdminSpots(),getAdminPOIPhotos()]); setReports(r);setSpots(s);setPhotos(p); };
  useEffect(()=>{refresh()},[isAdmin]);
  const visibleReports=useMemo(()=>reports.filter(r=>(filter==='all'||r.status===filter)&&(typeFilter==='all'||r.target_type===typeFilter)&&(reasonFilter==='all'||r.category===reasonFilter)&&(!q||JSON.stringify(r).toLowerCase().includes(q.toLowerCase()))),[reports,filter,typeFilter,reasonFilter,q]);
  if(isLoadingAuth)return <div className="p-10">Loading…</div>;
  if(!isAdmin) return <div className="min-h-screen flex items-center justify-center p-6 bg-slate-50 dark:bg-slate-950"><div className="w-full max-w-lg bg-white dark:bg-slate-900 border rounded-2xl p-6 shadow-sm"><h1 className="text-xl font-semibold">Admin access required</h1><p className="text-sm text-slate-500 mt-2">This area requires the Firebase <code>admin: true</code> custom claim.</p>{user?<p className="text-sm mt-4">Signed in as <strong>{user.email}</strong>.</p>:<p className="text-sm text-amber-600 mt-4">Sign in with an authorized admin account first.</p>}</div></div>;
  return <div className="min-h-screen bg-slate-50 dark:bg-slate-950 p-4 md:p-8"><div className="max-w-6xl mx-auto">
    <h1 className="text-2xl font-bold mb-1">SpotFinder Admin</h1><p className="text-sm text-slate-500 mb-6">Moderation and operations. Privileged writes run through logged Cloud Functions.</p>
    <div className="flex gap-2 flex-wrap mb-6">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`px-4 py-2 rounded-lg text-sm ${tab===t?'bg-slate-900 text-white':'bg-white border dark:bg-slate-900'}`}>{t}</button>)}</div>
    {tab==='Reports'&&<section><div className="flex gap-2 mb-4"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search reports, device, user…" className="flex-1 border rounded-lg px-3 py-2 bg-white dark:bg-slate-900"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="border rounded-lg px-3 bg-white dark:bg-slate-900"><option value="all">All statuses</option><option value="open">Open</option><option value="resolved">Resolved</option></select><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)} className="border rounded-lg px-3 bg-white dark:bg-slate-900"><option value="all">All targets</option><option value="spot">Spots</option><option value="poi">POIs</option><option value="poi_photo">POI photos</option></select><select value={reasonFilter} onChange={e=>setReasonFilter(e.target.value)} className="border rounded-lg px-3 bg-white dark:bg-slate-900"><option value="all">All reasons</option><option value="wrong_info">Wrong info</option><option value="wrong_location">Wrong location</option><option value="does_not_exist">Doesn't exist</option><option value="duplicate">Duplicate</option><option value="inappropriate">Inappropriate</option><option value="spam">Spam</option><option value="wrong_place">Wrong photo</option><option value="copyright">Copyright</option><option value="private_info">Private info</option><option value="misleading">Misleading</option><option value="other">Other</option></select></div>
      <div className="space-y-3">{visibleReports.map(r=><div key={r.id} className="bg-white dark:bg-slate-900 border rounded-xl p-4"><div className="flex justify-between gap-3"><div><span className="text-xs uppercase text-slate-500">{r.target_type||'other'} · {r.category||'other'} · {r.status||'open'}</span><h3 className="font-semibold">{r.subject||'Report'}</h3><p className="text-sm mt-2 whitespace-pre-wrap">{r.message || 'No additional details.'}</p>{r.target_snapshot&&<div className="mt-2 text-xs bg-slate-50 dark:bg-slate-800 rounded p-2"><strong>Target:</strong> {r.target_snapshot.title||r.target_snapshot.name||r.target_id}<br/><span className="break-all">ID: {r.target_id}</span></div>}<p className="text-xs text-slate-400 mt-2">{r.created_at} · reporter {r.reporter_uid||'guest'} · device {r.device_hash?.slice(0,12)||'n/a'}…</p></div><div className="flex gap-2 flex-wrap content-start justify-end"><button onClick={async()=>{await adminResolveReport(r.id);refresh()}} className="text-xs border rounded px-2 py-1">Resolve</button><button onClick={async()=>{await adminBlockReporter(r.id);refresh()}} className="text-xs border rounded px-2 py-1">Block spammer</button><button onClick={async()=>{if(confirm('Delete this report?')){await adminDeleteReport(r.id);refresh()}}} className="text-xs bg-red-600 text-white rounded px-2 py-1">Delete</button></div></div></div>)}</div></section>}
    {tab==='Spots'&&<section><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Filter spots…" className="w-full border rounded-lg px-3 py-2 mb-4 bg-white dark:bg-slate-900"/><div className="space-y-3">{spots.filter(s=>!q||JSON.stringify(s).toLowerCase().includes(q.toLowerCase())).map(s=><SpotRow key={s.id} spot={s} refresh={refresh}/>)}</div></section>}
    {tab==='Photos'&&<section><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{photos.map(p=><div key={p.id} className="bg-white dark:bg-slate-900 border rounded-xl overflow-hidden">{p.image&&<img src={p.image} className="w-full h-40 object-cover"/>}<div className="p-3"><p className="text-xs break-all">POI: {p.poi_id}</p><p className="text-xs text-slate-500">By {p.created_by}</p><button onClick={async()=>{if(confirm('Delete this photo?')){await adminDeletePOIPhoto(p.id);refresh()}}} className="mt-3 text-xs bg-red-600 text-white rounded px-3 py-1.5">Delete image</button></div></div>)}</div></section>}
    {tab==='Status'&&<div className="-mx-4 md:-mx-8 -mt-10"><StatusAdmin/></div>}
  </div></div>;
}
function SpotRow({spot,refresh}){ const [editing,setEditing]=useState(false); const [title,setTitle]=useState(spot.title||''); const [description,setDescription]=useState(spot.description||''); return <div className="bg-white dark:bg-slate-900 border rounded-xl p-4"><div className="flex gap-4 justify-between"><div className="flex-1">{editing?<><input value={title} onChange={e=>setTitle(e.target.value)} className="w-full border rounded p-2 mb-2 bg-transparent"/><textarea value={description} onChange={e=>setDescription(e.target.value)} className="w-full border rounded p-2 bg-transparent"/></>:<><h3 className="font-semibold">{spot.title||'Untitled'}</h3><p className="text-sm text-slate-500">{spot.description}</p></>}<p className="text-xs text-slate-400 mt-2">{spot.id} · {spot.status}</p></div><div className="flex gap-2 content-start">{editing?<button onClick={async()=>{await adminUpdateSpot(spot.id,{title,description});setEditing(false);refresh()}} className="text-xs border rounded px-2 py-1">Save</button>:<button onClick={()=>setEditing(true)} className="text-xs border rounded px-2 py-1">Edit</button>}{spot.image_url&&<button onClick={async()=>{if(confirm('Remove this spot image?')){await adminUpdateSpot(spot.id,{image_url:null});refresh()}}} className="text-xs border rounded px-2 py-1">Remove image</button>}<button onClick={async()=>{if(confirm('Permanently delete this spot?')){await deleteSpotAsSuperAdmin(spot.id);refresh()}}} className="text-xs bg-red-600 text-white rounded px-2 py-1">Delete</button></div></div></div> }
